<div class="container">
    <div class="row">
        <div class=" col-md-12">
            <ol class="breadcrumb">
                <li><a href="#">Cabinet</a></li>
                <li class="active">Courses</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class=" col-md-12">
            <button type="button" class="btn btn btn-success">
                Add a new course
            </button>

            <h4><br/>My courses: </h4>

            <div class="course_panel">
                <div class="course_panel_header">
                    <div class="course_name">
                        <a href="">PHP COURSE</a>
                    </div>
                    <div class="date_modification">
                        Date: 10-12-2015
                        <a href="">Edit </a>|
                        <a href=""> Delete</a>
                    </div>
                </div>
                <div class="course_img">
                    <img src="images/img_100.png" class="img-responsive" alt="Responsive image" width="100" height="100">
                </div>
                <div class="course_text">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec posuere purus augue, ac
                        placerat massa tempor ac.
                        Aenean sit amet est pellentesque, eleifend eros nec, condimentum velit. Donec leo odio,
                        consequat in hendrerit sed,
                        dapibus in ex. Nullam sed nulla vel nibh convallis scelerisque in vitae felis. Quisque
                        tempor diam eu nulla pulvinar tristique.
                        Donec eu urna vehicula, lacinia lacus pulvinar, rutrum leo. Vivamus commodo pretium urna sit
                        amet condimentum. Maecenas
                        ac nunc eleifend, sagittis nibh nec, ultricies massa. Donec posuere venenatis magna
                        efficitur suscipit. Praesent eget
                        eros vel quam volutpat ornare. Suspendisse potenti.Ut sed nunc nibh. Etiam consectetur, est
                        ut venenatis consectetur,
                        quam lectus finibus sapien, eu sodales magna elit in tellus. Ut mattis tempus mi nec
                        sollicitudin.
                        Aenean ornare eleifend lorem vel porta. Ut maximus ultrices sollicitudin. Proin ut consequat
                        diam.
                        Sed rhoncus dolor eu justo condimentum, vel laoreet enim imperdiet. Pellentesque eleifend,
                        nunc id interdum imperdiet,
                        ante orci iaculis enim, et vulputate odio odio et libero. In non nisi luctus, fringilla
                        ipsum id, maximus eros.
                        Nam id ullamcorper turpis, vitae rutrum ligula. Proin sagittis libero mi, non maximus ipsum
                        aliquet vel.
                        Aenean volutpat massa ultricies finibus viverra. Maecenas consectetur ante vitae volutpat
                        dictum. Ut iaculis, lacus laoreet
                        pretium eleifend, felis nulla cursus tortor, non consectetur diam magna ac leo. Donec
                        sagittis hendrerit est, sed tincidunt lectus lobortis eget.
                    </p>
                </div>
                <div class="row">
                    <div class=" col-md-5">
                        <div class="course_rating">
                            Rating: <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </div>
                    </div>
                    <div class=" col-md-2">
                        <div class="course_status">Status: published</div>
                    </div>
                    <div class=" col-md-5">
                        <div class="course_submit"><a href="">Submit to review</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
