	<div class="container">
		<div class="col-md-12">
			<nav class="row">
					<ol class="breadcrumb">
						<li><a href="">Главная</a></li>
						<li><a href="">Настройки</a></li>
						<li class="active">Курсы</li>
					</ol>
			</nav>
			<div class="row">
				<div class="col-md-offset-3 col-md-9">
					<header>
							<h1>Курсы</h1>
						</header>
				</div>
			</div>
			<div class="row">
				<aside class="col-md-3">
					<div class="menu well">
						<ul class="nav nav-pills nav-stacked">
							<li class="active"><a href="/">Курсы</a></li>
							<li><a href="">Авторы</a></li>
							<li><a href="">Пользователи</a></li>
							<li><a href="">Категории</a></li>
						</ul>
					</div>
				</aside>
				<section class="col-md-9 main-content admin-page courses">
					<div class="well">
						<a href="#" class="btn btn-primary btn-sm pull-right"><b>+</b>Добавить курс</a>
						<table class="table table-striped table-condensed table-hover">
							<colgroup>
								<col width="45">
								<col width="120">
								<col width="114">
								<col width="125">
								<col width="115">
								<col width="110">
								<col width="75">
								<col width="95">
								<col width="100">
							</colgroup>
					    <thead>
					        <tr>
					            <th>№</th>
					            <th>Курс <span class="caret"></span></th>
					            <th>Категория <span class="caret"></span></th>
					           	<th>Рейтинг <span class="caret"></span></th>
					           	<th>Добавил <span class="caret"></span></th>
					           	<th>Создан <span class="caret"></span></th>
					           	<th>Учат <span class="caret"></span></th>
					           	<th>Прошли <span class="caret"></span></th>
					            <th class="text-right">Действия</th>
					        </tr>
					    </thead>
					            <tr>
					                <td>1</td>
					                <td>
					                	<a href="">PHP Основы, курс лекций</a>
					                </td>
					                <td><a href="">PHP</a></td>
					                <td><a href="">
					                	<p class="rating-stars pull-right">
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star-empty'></span>
									</p>
					                </a></td>
					                <td><a href="">
					                	<a href="#">Иван Царевич</a>
					                </a></td>
					                <td><a href="">11-12-2015</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td class="text-right">
					                	<div class="pull-right switch">
									        <input id="cmn-toggle-1" class="cmn-toggle cmn-toggle-round-flat" type="checkbox">
									        <label for="cmn-toggle-1"></label>
								        </div>
										<div class="btn-container center-block">
											<a class='btn btn-admin btn-info btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> edit</a>
										</div>
										<div class="btn-container center-block">
											<a href="#" class="btn btn-admin btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> delete</a>
										</div>
					                 </td>
					            </tr>
					            <tr>
					                <td>2</td>
					                <td>
					                	<a href="#">JavsScript Основы, 12 видео-уроков, тестирование.</a>
					                </td>
					                <td><a href="#">JavsScript</a></td>
					                <td><a href="">
					                	<p class="rating-stars pull-right">
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star-empty'></span>
									</p>
					                </a></td>
					                <td><a href="">Василиса Премудрая</a></td>
					                <td><a href="">11 декабря 2015</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td class="text-right">
					                	<div class="pull-right switch">
									        <input id="cmn-toggle-2" class="cmn-toggle cmn-toggle-round-flat" type="checkbox">
									        <label for="cmn-toggle-2"></label>
								        </div>
										<div class="btn-container center-block">
											<a class='btn btn-admin btn-info btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> edit</a>
										</div>
										<div class="btn-container center-block">
											<a href="#" class="btn btn-admin btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> delete</a>
										</div>
					                 </td>
					            </tr>
					            <tr>
					                <td>3</td>
					                <td>
					                	<a href="">Оптимизация SQL запросов,  12 видео-уроков, тестирование, + бесплатная книга для скачивания</a>
					                </td>
					                <td><a href="">MySQL</a></td>
					                <td><a href="">
					                	<p class="rating-stars pull-right">
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star'></span>
										<span class='glyphicon glyphicon-star-empty'></span>
									</p>
					                </a></td>
					                <td><a href="">Баба Яга</a></td>
					                <td><a href="">11 декабря 2015</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td><a href="#"><span class="glyphicon glyphicon-user"></span> 24</a></td>
					                <td class="text-right">
					                	<div class="pull-right switch">
									        <input id="cmn-toggle-3" class="cmn-toggle cmn-toggle-round-flat" type="checkbox">
									        <label for="cmn-toggle-3"></label>
								        </div>
										<div class="btn-container center-block">
											<a class='btn btn-admin btn-info btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> edit</a>
										</div>
										<div class="btn-container center-block">
											<a href="#" class="btn btn-admin btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> delete</a>
										</div>
					                 </td>
					            </tr>
					    </table>
					</div>
				</section><!-- ./col-md-10 main-content admin-page courses -->
			</div><!-- ./row -->
		</div><!-- ./col-md-12 -->
	</div><!-- ./container -->
