<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>itcourses | Admin - Landing</title>
	<link rel="stylesheet" href="../public/css/bootstrap.css">
	<!-- Подключаю свои стили -->
	<link rel="stylesheet" href="../public/css/main.css">
	<link rel="stylesheet" href="../public/css/style.css">
    <!-- tinyMCE -->
	<script src="../public/tinymce/tinymce.min.js"></script>
    <script src="../public/js/tinymce.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-default navbar-fixed-top top-menu-black">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed burger-button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#"><b>ITCourses</b></a>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="header_text_al">
                                    <a href="#">
                                        <span class="glyphicon glyphicon-comment"></span>
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" id="pad_null" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">My Courses</a>
                                        </li>
                                        <li>
                                            <a href="#">View Profile</a>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li>
                                            <a href="#">Log out</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <form class="navbar-form" id="search" role="search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
	<div class="container">
		<div class="col-md-12">
			<nav class="row">
					<ol class="breadcrumb">
						<li><a href="">Главная</a></li>
						<li><a href="">Настройки</a></li>
						<li class="active">Landing</li>
					</ol>
			</nav>
			<header class="row">
				<div class="col-xs-offset-2 col-xs-10">
					<h1>Landing page</h1>
				</div>
			</header>
			<div class="row">
				<aside class="col-md-2 menu">
					<div class="well">
						<ul class="nav nav-pills nav-stacked">
							<li><a href="/">Курсы</a></li>
							<li><a href="">Авторы</a></li>
							<li class="active"><a href="">Пользователи</a></li>
							<li><a href="">Категории</a></li>
						</ul>
					</div>
				</aside>
				<section class="col-md-10 main-content admin-page users">
					<div class="well">
						<section class="slides row">
                            <div class="col-md-offset-1 col-md-10">
                                <header>
                                    <h2 class="text-center">Слайды</h2>
                                </header>
                                <button type="button" class="btn btn-primary btn-lg center-block" role="button" data-toggle="collapse" href="#collapseExample"><span class="glyphicon glyphicon-plus"></span> Добавить слайд</button>
                               
                                <div class="row collapse" id="collapseExample">
                                    
                                    <div class="col-md-8">
                                        <header>
                                            <h3>Слайд #1</h3>
                                        </header>
                                        <img class="img-responsive" src="../public/images/slide1.png" alt="slide1 2338 x 664"/>
                                    </div>
                                    <div class="col-md-4">
                                        <p>
                                            <em>slide1.png 2338 x 664</em>
                                        </p>
                                        <a href="#" class="btn btn-default">Изменить</a>
                                    </div>
                                    <div class="col-md-8">
                                        <form method="post">
                                            <div class="form-group">
                                                <label for="inputSliderOne">Заголовок:</label>
                                                <input type="text" class="form-control" id="inputSliderOne" placeholder="IT Courses">
                                                <label for="inputSliderText">Текст слайда:</label>
                                                <input type="text" class="form-control" id="inputSliderText" placeholder="The first free educational resource">
                                              </div>
                                         </form>     
                                    </div>
                                    <div class="col-md-4">
                                        <label for="selectSlideOrder">Номер в очереди:</label>
                                        <select id="selectSlideOrder">
                                          <option value="1">1</option>
                                          <option value="2">2</option>
                                          <option value="3">3</option>
                                        </select>

                                    </div>

                                    <div class="col-md-12">
                                        <button type="button" class="btn btn-default pull-right">Сохранить слайд</button>
                                        <button type="button" class="btn btn-primary btn-lg center-block" role="button" data-toggle="collapse" href="#collapseExample"><span class="glyphicon glyphicon-plus"></span> Добавить слайд</button>
                                    </div>                                        
                                </div>
                            </div>
                        </section>
                        <section class="mission row">
                            <div class="col-md-offset-1 col-md-10">
                                <header>
                                    <h3 class="text-center">Миссия</h3>
                                </header>
                                    <form method="post">
                                        <textarea id="textMission" class="tinymce">Lorem ipsum dапвапвапвolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulputate commodo lectus, ac blandit elit tincidunt id. Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus Lorem ipsum dапвапвапвolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulputate commodo lectus, ac blandit elit tincidunt id. Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus</textarea>
                                    </form>
                                <button type="button" class="btn btn-primary pull-right">Сохранить миссию</button>
                           </div>
                        </section>
                        <section class="promo row">
                            <header>
                                <h3 class="text-center">Настройки блока "How its work?"</h3>
                            </header>
                            <article class="col-md-offset-1 col-md-10 well">
                                <div class="row">
                                    <div class="col-md-5">
                                        <img src="../public/images/learn.jpg" alt="" class="img-responsive">
                                        <p><em>slide1.png 2338 x 664</em></p>
                                        <button class="btn btn-default pull-right">Изменить</button>
                                    </div>
                                    <div class="col-md-7">
                                        <form method="post">
                                            <div class="form-group">
                                                <label for="headerHowItsWork">Заголовок:</label>
                                                <input type="email" class="form-control" id="headerHowItsWork" placeholder="Simple way to learn: something new">
                                              </div>
                                            <label for="textHowItsWork">Текст:</label>
                                            <textarea id="textHowItsWork" class="tinymce">Lorem ipsum dolor sit amet, consectetur adipisicing elit. aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat Ad, architecto asperiores aut cum deleniti ducimus error, ex fugiat.</textarea>
                                        </form>
                                    </div>
                                    
                                    <div class="col=md-12">
                                        <button type="button" class="btn btn-default pull-right">Сохранить</button>
                                    </div>
                                </div>
                            </article>
                            <article class="col-md-12 well">
                                <div class="row">
                                    <div class="col-md-5">
                                        <img src="../public/images/learn.jpg" alt="" class="img-responsive">
                                        <p><em>slide1.png 2338 x 664</em></p>
                                        <button class="btn btn-default pull-right">Изменить</button>
                                    </div>
                                    <div class="col-md-7">
                                        <form method="post">
                                            <div class="form-group">
                                                <label for="headerHowItsWorksPart2">Заголовок:</label>
                                                <input type="text" class="form-control" id="headerHowItsWorksPart2" placeholder="Simple way to learn: something new">
                                              </div>
                                            <label for="textHowItsWorksPart2">Текст:</label>
                                            <textarea id="textHowItsWorksPart2" class="tinymce">Lorem ipsum dolor sit amet, consectetur adipisicing elit. aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat Ad, architecto asperiores aut cum deleniti ducimus error, ex fugiat.</textarea>
                                        </form>
                                    </div>
                                    
                                    <div class="col=md-12">
                                        <button type="button" class="btn btn-default pull-right">Сохранить</button>
                                    </div>
                                </div>
                            </article>

                            <article class="col-md-12 well">
                                <div class="row">
                                    <div class="col-md-5">
                                        <img src="../public/images/learn.jpg" alt="" class="img-responsive">
                                        <p><em>slide1.png2338 x 664</em></p>
                                        <button class="btn btn-default pull-right">Изменить</button>
                                    </div>
                                    <div class="col-md-7">
                                        <form method="post">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Заголовок:</label>
                                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Simple way to learn: something new">
                                              </div>
                                            <label for="exampleInputEmail1">Текст:</label>
                                            <textarea class="tinymce">Lorem ipsum dolor sit amet, consectetur adipisicing elit. aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat Ad, architecto asperiores aut cum deleniti ducimus error, ex fugiat.</textarea>
                                        </form>
                                    </div>
                                    
                                    <div class="col=md-12">
                                        <button type="button" class="btn btn-default pull-right">Сохранить</button>
                                    </div>
                                </div>
                            </article>
                            
                        </section>
                        <section class="team row">
                            <div class="col-md-offset-2 col-md-8">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Фото</th>
                                        <th>Имя Фамилия</th>
                                        <th>Должность</th>
                                        <th>Выбрать</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td><img src="../public/images/author_house.jpg" alt="" class="img-responsive"></td>
                                        <td><a href="#">Name Surname</a></td>
                                        <td>PHP-developer</td>
                                        <td><input type="checkbox" id="blankCheckbox1" value="option1" aria-label="..."></td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td><img src="../public/images/author_house.jpg" alt="" class="img-responsive"></td>
                                        <td><a href="#">Name Surname</a></td>
                                        <td>PHP-developer</td>
                                        <td><input type="checkbox" id="blankCheckbox2" value="option1" aria-label="..."></td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td><img src="../public/images/author_house.jpg" alt="" class="img-responsive"></td>
                                        <td><a href="#">Name Surname</a></td>
                                        <td>PHP-developer</td>
                                        <td><input type="checkbox" id="blankCheckbox3" value="option1" aria-label="..."></td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td><img src="../public/images/author_house.jpg" alt="" class="img-responsive"></td>
                                        <td><a href="#">Name Surname</a></td>
                                        <td>PHP-developer</td>
                                        <td><input type="checkbox" id="blankCheckbox4" value="option1" aria-label="..."></td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td><img src="../public/images/author_house.jpg" alt="" class="img-responsive"></td>
                                        <td><a href="#">Name Surname</a></td>
                                        <td>PHP-developer</td>
                                        <td><input type="checkbox" id="blankCheckbox5" value="option1" aria-label="..."></td>
                                    </tr>
                                </tbody>
                            </table>
                            <button type="button" class="btn btn-default center-block">Сохранить A-Team</button>
                            </div>
                        </section>
					</div>
				</section><!-- ./col-md-10 main-content admin-page users -->
			</div>
		</div>
	</div>
<!--FOOTER-->
<footer id="footer" >
    <div class="container-fluid">
        <div class="navbar navbar-default">
            <div class="container col-md-12 text-center">
                    <div class="row text-center">
                        <ul class="nav navbar-nav navbar-center footer-menu">
                            <li><a href="#">Courses</a></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><a href="#">About us</a></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><a href="#">Contacts</a></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><a href="#">Sitemap</a></li>
                        </ul>
                    </div>
                    <div class="row">
                        <p class="navbar-center copyright-mar">Copyright &copy; 2015 - Free education
                            <a href="#" >ITCourses.com</a>
                        </p>
                    </div>
            </div>
        </div>
    </div>
</footer>	
<script src="../public/js/jquery-1.11.3.min.js"></script>
<script src="../public/js/bootstrap.min.js"></script>
</body>
</html>