<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <nav class="row">
                <ol class="breadcrumb">
                    <li><a href="">Главная</a></li>
                    <li class="active">Настройки</li>
                </ol>
            </nav>

            <div class="row">
                <header class="col-xs-offset-3 col-xs-9">
                    <h1>Настройки</h1>
                </header>
            </div>

            <div class="row">
                <aside class="col-md-3">
                    <div class="sidebar-menu well">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a href="/">Настройки</a></li>
                            <li><a href="">Авторы</a></li>
                            <li><a href="">Пользователи</a></li>
                            <li><a href="">Категории</a></li>
                        </ul>
                    </div>
                </aside>
                <section class="col-md-9 main-content cabinet">
                    <div class="well">
                        <section class="row courses">
                            <header class="col-md-12">
                                <h2>Последние добавленные курсы</h2>
                            </header>
                            <table class="table table-striped table-condensed table-hover">
                                <colgroup>
                                    <col width="50">
                                    <col width="420">
                                </colgroup>
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Название</th>
                                    <th>Автор</th>
                                    <th>Дата</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>{{courseNumber}}</td>
                                    <td><a href="#">{{courseName}}</a></td>
                                    <td>{{courseCreator}}</td>
                                    <td>{{courseDateCreation}}</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-success btn-sm' href="#\blockAction?id={{courseNumber}}"><span class="glyphicon glyphicon-edit"></span> #\blockAction?id={{courseNumber}}</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#\deleteAction?id={{courseNumber}}"><span class="glyphicon glyphicon-edit"></span> #\deleteAction?id={{courseNumber}}</a>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td><a href="#">Курс о том как создавать курсы</a></td>
                                    <td>Иван Царевич</td>
                                    <td>10-11-2015</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-success btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td><a href="#">Курс о том как создавать курсы</a></td>
                                    <td>Иван Царевич</td>
                                    <td>10-11-2015</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-success btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                        </div></td>
                                </tr>

                                </tbody>

                            </table>
                            <a class="btn btn-primary btn-sm pull-right" href="#">Все курсы</a>
                        </section>
                        <section class="row comments">
                            <header class="col-md-12">
                                <h2>Последние коментарии</h2>
                            </header>
                            <table class="table table-striped table-condensed table-hover">
                                <colgroup>
                                    <col width="50">
                                    <col width="350">
                                </colgroup>
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Коментарий</th>
                                    <th>Автор</th>
                                    <th>Курс</th>
                                    <th>Дата</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.</td>
                                    <td><a href="#">Губка Боб</a></td>
                                    <td><a href="#">SQL основы</a></td>
                                    <td>15-12-2015</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.</td>
                                    <td><a href="#">Губка Боб</a></td>
                                    <td><a href="#">SQL основы</a></td>
                                    <td>15-12-2015</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.</td>
                                    <td><a href="#">Губка Боб</a></td>
                                    <td><a href="#">SQL основы</a></td>
                                    <td>15-12-2015</td>
                                    <td><div class="btn-container center-block">
                                        <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                    </div>
                                        <div class="btn-container center-block">
                                            <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                        </div></td>
                                </tr>
                                </tbody>
                            </table>
                            <a class="btn btn-primary btn-sm pull-right" href="#">Все коментарии</a>
                        </section>
                        <section class="row users">
                            <header class="col-md-12">
                                <h2>Новые пользователи</h2>
                            </header>
                            <div class="col-md-12">
                                <table class="table table-striped table-condensed table-hover">
                                    <colgroup>
                                        <col width="50">
                                        <col width="200">
                                        <col width="500">
                                    </colgroup>
                                    <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Имя</th>
                                        <th>email</th>					<th>Действия</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Иван Царевич</td>
                                        <td>zar@batya.com</td>
                                        <td><div class="btn-container center-block">
                                            <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                        </div>
                                            <div class="btn-container center-block">
                                                <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                            </div></td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Царевна Лягушка</td>
                                        <td>kvakav@mail.com</td>
                                        <td><div class="btn-container center-block">
                                            <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                        </div>
                                            <div class="btn-container center-block">
                                                <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                            </div></td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Губга Боб</td>
                                        <td>bob@mail.com</td>
                                        <td><div class="btn-container center-block">
                                            <a class='btn btn-admin btn-warning btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Блок</a>
                                        </div>
                                            <div class="btn-container center-block">
                                                <a class='btn btn-admin btn-danger btn-sm' href="#"><span class="glyphicon glyphicon-edit"></span> Удалить</a>
                                            </div></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <a class="btn btn-primary btn-sm pull-right" href="#">+ Добавить пользователя</a>
                        </section>

                    </div><!-- ./well -->
                </section><!-- ./col-md-9 main-content cabinet-->
            </div><!-- ./row -->
        </div><!-- ./col-md-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
