
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <p>Categories</p>
                    <ul class="nav nav-pills nav-stacked">
                        <li role="presentation" class="active"><a href="#">PHP</a></li>
                        <li role="presentation"><a href="#">Java</a></li>
                        <li role="presentation"><a href="#">C#</a></li>
                        <li role="presentation"><a href="#">C++</a></li>
                        <li role="presentation"><a href="#">Scala</a></li>
                        <li role="presentation"><a href="#">MySQL</a></li>
                        <li role="presentation"><a href="#">Javascript</a></li>
                        <li role="presentation"><a href="#">HTML</a></li>
                        <li role="presentation"><a href="#">CSS</a></li>
                    </ul>
                </div>
                <div class="col-md-9">
                    <div class="row well">
                        <div class="col-md-12 well cursor-pointer">
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="#">PHP Course</a>
                                </div>
                                <div class="col-md-10">
                                    <div class="pull-right">
                                        <span>Date: </span>
                                        <span>10-22-2015</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-2">
                                        <img src="../public/images/course.png" alt="course" class="img-responsive"/>
                                        <span>Rating</span>
                                    </div>
                                    <div class="col-md-10">
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
                                            Duis vulputate commodo lectus, ac blandit elit tincidunt id.
                                            Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui.
                                            Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.
                                            Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit.
                                            Vivamus varius pretium ligula, a aliquam odio euismod sit amet.
                                            Quisque laoreet sem sit amet orci ullamcorper at ultricies metus viverra.
                                            Pellentesque arcu mauris, malesuada quis ornare accumsan, blandit sed diam.
                                        </span>
                                    </div>
                            </div>
                        </div>
                        <div class="col-md-12 well cursor-pointer">
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="#">Java Course</a>
                                </div>
                                <div class="col-md-10">
                                    <div class="pull-right">
                                        <span>Date: </span>
                                        <span>10-15-2015</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <img src="../public/images/course.png" alt="course" class="img-responsive"/>
                                    <span>Rating</span>
                                </div>
                                <div class="col-md-10">
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
                                            Duis vulputate commodo lectus, ac blandit elit tincidunt id.
                                            Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui.
                                            Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.
                                            Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit.
                                            Vivamus varius pretium ligula, a aliquam odio euismod sit amet.
                                            Quisque laoreet sem sit amet orci ullamcorper at ultricies metus viverra.
                                            Pellentesque arcu mauris, malesuada quis ornare accumsan, blandit sed diam.
                                        </span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 well cursor-pointer">
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="#">MySQL Course</a>
                                </div>
                                <div class="col-md-10">
                                    <div class="pull-right">
                                        <span>Date: </span>
                                        <span>10-08-2015</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <img src="../public/images/course.png" alt="course" class="img-responsive"/>
                                    <span>Rating</span>
                                </div>
                                <div class="col-md-10">
                                        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
                                            Duis vulputate commodo lectus, ac blandit elit tincidunt id.
                                            Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui.
                                            Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.
                                            Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit.
                                            Vivamus varius pretium ligula, a aliquam odio euismod sit amet.
                                            Quisque laoreet sem sit amet orci ullamcorper at ultricies metus viverra.
                                            Pellentesque arcu mauris, malesuada quis ornare accumsan, blandit sed diam.
                                        </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
