
<div class="container">
	<div class="row">
	    <div class="col-xs-12">
			<nav class="row">
					<ol class="breadcrumb">
						<li><a href="">Главная</a></li>
						<li class="active">Мое обучение</li>
					</ol>
			</nav>

	        <div class="row">
	            <header class="col-xs-offset-3 col-xs-9">
	                <h1>Мое обучение</h1>
	            </header>
	        </div>

	        <div class="row">
	            <aside class="col-md-3">
	                <div class="sidebar-menu well">
	                    <ul class="nav nav-pills nav-stacked">
	                        <li class="active"><a href="/">Мое обучение</a></li>
	                        <li><a href="">Мои курсы</a></li>
	                        <li><a href="">Создать курс</a></li>
	                    </ul>
	                </div>
	            </aside>
	            <section class="col-md-9 main-content cabinet">
	                <div class="well">
	                    <div class="row">
	                        <div class="col-md-12">
	                            <header class="row">
	                                <div class="col-md-9">
	                                    <h1>Основы PHP</h1>
	                                </div>
	                                <div class="col-md-3">
	                                    <p class="date">11 декабря 2015</p>
	                                </div>
	                            </header>
	                            <div class="row">
	                                <div class="col-md-2">
	                                    <ul class="nav nav-pills nav-stacked">
	                                        <li><a href="/">Лекция 1</a></li>
	                                        <li class="active"><a href="/">Лекция 2</a></li>
	                                        <li><a href="/">Лекция 3</a></li>
	                                        <li><a href="/">Лекция 4</a></li>
	                                        <li><a href="/">Лекция 5</a></li>
	                                        <li><a href="/">Лекция 6</a></li>
	                                    </ul>
	                                </div><!--./col-md-2 -->
	                                <div class="col-md-5">
	                                    <section class="about-lecture">
	                                        <header>
	                                            <h3>Вы научитесь:</h3>
	                                        </header>
	                                        <section class="about-lecture-content">
	                                            <p>
	                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulputate commodo lectus, ac blandit elit tincidunt id. Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam. Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit.
	                                            </p>
	                                            <a href="/">Пройти тест</a>
	                                        </section>
	                                        <div class="center-block">
	                                        	<div class="buttons">
	                                            	<a class="btn btn-info btn-lg" href="#">перейти к лекции</a>
	                                            </div>
	                                        </div>
	                                    </section>    
	                                </div><!-- ./col-md-5 -->
	                            	<div class="col-md-5">
									<section class="rating" data-toggle="popover" data-triger="hover">
										<header>
											<h3>Оцените курс</h3>
										</header>
										<section>
											<p class="rating-stars pull-left">
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star-empty'></span>
											</p>

											<a href="/" class="pull-left">Оцените курс</a>
											

										</section>

									</section>
									<section class="lecture-materials clearfix">
										<header>
											<h3>Материалы по теме:</h3>
										</header>
										<section class="lecture-materials-links">
											<ul class="list-unstyled">
												<li>
													<span class="glyphicon glyphicon-download"></span>
													<a href="/">Примеры кода</a> 2mb
												</li>
												<li>
													<span class="glyphicon glyphicon-download"></span>
													<a href="/">Лабораторная работа №1</a> 0.5mb
												</li>
												<li>
													<span class="glyphicon glyphicon-link"></span>
													<a href="/">Лабораторная работа №1</a> 0.5mb
												</li>
											</ul>
										</section>
									</section>
								</div><!-- ./col-md-5 -->
								</div><!-- ./row -->
							</div><!-- ./col-md-12 -->
						</div><!-- ./row -->
					</div><!-- ./well -->
				</section><!-- ./col-md-9 main-content cabinet-->
	        </div><!-- ./row -->
	        <div class="row">
				<section class="col-md-offset-3 col-md-9 courses-in-progress">
					<div class="well">	
						<div class="row">
							<div class="col-md-12">
								<header>
									<h3>Курсы в процессе</h3>
								</header>
							</div><!-- ./col-md-12 -->
						</div><!-- ./row -->
						<div class="row">
							<div class="col-md-12 well cursor-pointer">
	                            <div class="row">
	                                <div class="col-md-9">
	                                   <h4><a href="#">SQL advanced course</a></h4>
	                                   <h5>lecture 4</h5>
	                                </div>
	                                <div class="col-md-3">
	                                    <div class="pull-right">
	                                        <p class="date">Date: 10-22-2015</p>
	                                    </div>
	                                </div>
	                            </div>
	                            <div class="row">
	                                <div class="col-md-2">
	                                    <img class="img-responsive" src="../public/images/course.png" alt="course"/>
	                                    <p>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star'></span>
												<span class='glyphicon glyphicon-star-empty'></span>
											</p>
	                                </div>
	                                <div class="col-md-10">
	                                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	                                        Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
	                                        Duis vulputate commodo lectus, ac blandit elit tincidunt id.
	                                        Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui.
	                                        Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam.
	                                        Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit.
	                                        Vivamus varius pretium ligula, a aliquam odio euismod sit amet.
	                                    </div>
	                                    <div class="buttons center-block clearfix">
	                                    	<a class="btn btn-info btn-lg" href="#">перейти к лекции</a>
	                                    </div>
	                                </div>
	                            </div>
	                            
	                        </div>
                        </div><!-- ./row -->
					</div><!-- ./well -->
				</section><!-- ./col-md-12 courses-in-progress -->
			</div><!-- ./row -->
			<div class="row">
				<section class="col-md-offset-3 col-md-9 passed-courses">
					<div class="well">
						<div class="row">
							<div class="col-md-12">
								<header>
									<h3>Завершенные курсы</h3>
								</header>
							</div><!-- ./col-md-12 -->
						</div><!-- ./row -->
						<div class="row">
							<div class="col-md-12 well cursor-pointer">
	                            <div class="row">
	                                <div class="col-md-9">
	                                   <h4><a href="#">SQL basics course</a></h4>
	                                </div>
	                                <div class="col-md-3">
	                                    <div class="pull-right">
	                                        
	                                        <span>Date: 10-22-2015</span>
	                                    </div>
	                                </div>
	                            </div>
	                            <div class="row">
	                                <div class="col-md-2">
	                                    <img src="../public/images/course.png" alt="course" class="img-responsive"/>
	                                    <p>
											<span class='glyphicon glyphicon-star'></span>
											<span class='glyphicon glyphicon-star'></span>
											<span class='glyphicon glyphicon-star'></span>
											<span class='glyphicon glyphicon-star'></span>
											<span class='glyphicon glyphicon-star-empty'></span>
										</p>
	                                </div>
	                                <div class="col-md-10">
	                                	<div class="row">
	                                		<div class="col-md-8">
	                                			<table class="table table-hover ">
			                                		<thead>
			                                			<tr>
			                                				<th class="text-center" colspan="2">Результаты</th>
			                                			</tr>
			                                		</thead>
			                                		<tbody>
			                                			<tr>
			                                				<td>Лекций 6</td>
			                                				<td>Средний бал: 85</td>
			                                			</tr>
			                                			
			                                		</tbody>
			                                	</table>
			                                	<p>You have passed The SQL basics course, successfully.</p>	
	                                		</div>
	                                		<div class="col-md-4">
	                                			<img class="img-responsive" src="../public/images/congratulations.jpg" alt="congratulations">
	                                		</div>
	                                	</div>
	                                </div>
	                            </div>
	                        </div>
                        </div><!-- ./row -->
					</div><!-- ./well -->
				</section><!-- ./col-md-12 passed-courses-->				
			</div><!-- ./row -->
	    </div><!-- ./col-md-12 -->
	</div><!-- ./row -->
</div><!-- ./container -->
